### ISSUE TITLE
【每周算法】55. 跳跃游戏

### ISSUE THREAD

**Issue by flipped598** [minibear2333/interview-leetcode#13]
给定一个非负整数数组，你最初位于数组的第一个位置。

数组中的每个元素代表你在该位置可以跳跃的最大长度。

判断你是否能够到达最后一个位置。

示例 1:

输入: [2,3,1,1,4]
输出: true
解释: 我们可以先跳 1 步，从位置 0 到达 位置 1, 然后再从位置 1 跳 3 步到达最后一个位置。
示例 2:

输入: [3,2,1,0,4]
输出: false
解释: 无论怎样，你总会到达索引为 3 的位置。但该位置的最大跳跃长度是 0 ， 所以你永远不可能到达最后一个位置。

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/jump-game

**Comment by QiuChenI** [comment]
思路1
由例子可以看出 只要0以前的数能跳过0就可以跳到最后一个位置
这个时候只需后序遍历 ，遇到0就检测，如果跳不到0之后就不能到达最后位置返回false  
代码如下：

class Solution {
    public boolean canJump(int[] nums) {
		if(nums.length==1)
		{
			return true;
		}
        A:for(int i = nums.length-2;i>=0;i--)
        {
        	if(nums[i]==0)
        	{
        		int index = 0;
        		while(index<i)
        		{
        			if(nums[index]+index>i)
        			{
        				continue A;
        			}
        			index++;
        		}
        		return false;
        	}
        }
		return true;
    }
}
时间复杂度  O（n²）   空间复杂度 O（1）

思路2
每个位置的数字是他能跳的最大长度。也就是说“本地位置+最大长度>=数组长度-1” 就是能跳过，
如果直接计算他的“本地位置+最大长度“会将跳到不了的地方也计算进去导致结果不符。
解决方法就是增加距离检测   将已遍历到的数据中跳的最远距离记录出来 进行判断 如果能达到当前位置就继续进行计算反之跳出循环。
代码如下：
class Solution {
    public boolean canJump(int[] nums) {
	int max = nums[0];
        for(int i = 0;i<nums.length;i++)
        {
        	if(max>=i)
        	{
        		max = max<(nums[i]+i)?(nums[i]+i):max;
        	}else
        	{
        		break;
        	}
        }
        return max>=nums.length-1;
    }
}

时间复杂度  O（n）   空间复杂度 O（1）

**Comment by QiuChenI** [comment]
思路1 
由例子可以看出只要0以前的数能跳过0就可以跳到最后一个位置
这个时候只需后序遍历，遇到0就检测，如果跳不到0之后就不能到达最后位置返回false 
代码如下：
`class Solution {
    public boolean canJump(int[] nums) {
		if(nums.length==1)
		{
			return true;
		}
        A:for(int i = nums.length-2;i>=0;i--)
        {
        	if(nums[i]==0)
        	{
        		int index = 0;
        		while(index<i)
        		{
        			if(nums[index]+index>i)
        			{
        				continue A;
        			}
        			index++;
        		}
        		return false;
        	}
        }
		return true;
    }
}`
时间复杂度O（n²）空间复杂度O（1）

思路2 
每个位置的数字是他能跳的最大长度。也就是说“本地位置+最大长度>=数组长度-1”就是能跳过，
如果直接计算他的“本地位置+最大长度“会将跳到不了的地方也计算进去导致结果不符。
解决方法就是增加距离检测将已遍历到的数据中跳的最远距离记录出来进行判断如果能达到当前位置就继续进行计算反之跳出循环。
代码如下：
`class Solution {
    public boolean canJump(int[] nums) {
		int max = nums[0];
        for(int i = 0;i<nums.length;i++)
        {
        	if(max>=i)
        	{
        		max = max<(nums[i]+i)?(nums[i]+i):max;
        	}
        }
        return max>=nums.length-1;
    }
}`

时间复杂度O（n） 空间复杂度O（1）

**Comment by QiuChenI** [comment]
`class Solution {
    public boolean canJump(int[] nums) {
		int max = nums[0];
        for(int i = 0;i<nums.length;i++)
        {
        	if(max>=i)
        	{
        		max = max<(nums[i]+i)?(nums[i]+i):max;
        	}
        }
        return max>=nums.length-1;
    }
}`

**Comment by QiuChenI** [comment]
````
class Solution {
    public boolean canJump(int[] nums) {
		int max = nums[0];
        for(int i = 0;i<nums.length;i++)
        {
        	if(max>=i)
        	{
        		max = max<(nums[i]+i)?(nums[i]+i):max;
        	}
        }
        return max>=nums.length-1;
    }
}
````

**Comment by QiuChenI** [comment]
思路1 
由例子可以看出只要0以前的数能跳过0就可以跳到最后一个位置
这个时候只需后序遍历，遇到0就检测，如果跳不到0之后就不能到达最后位置返回false 
代码如下：
````
class Solution {
    public boolean canJump(int[] nums) {
		if(nums.length==1)
		{
			return true;
		}
        A:for(int i = nums.length-2;i>=0;i--)
        {
        	if(nums[i]==0)
        	{
        		int index = 0;
        		while(index<i)
        		{
        			if(nums[index]+index>i)
        			{
        				continue A;
        			}
        			index++;
        		}
        		return false;
        	}
        }
		return true;
    }
}
````
时间复杂度O（n²）空间复杂度O（1）

思路2 
每个位置的数字是他能跳的最大长度。也就是说“本地位置+最大长度>=数组长度-1”就是能跳过，
如果直接计算他的“本地位置+最大长度“会将跳到不了的地方也计算进去导致结果不符。
解决方法就是增加距离检测将已遍历到的数据中跳的最远距离记录出来进行判断如果能达到当前位置就继续进行计算反之跳出循环。
代码如下：
````
class Solution {
    public boolean canJump(int[] nums) {
		int max = nums[0];
        for(int i = 0;i<nums.length;i++)
        {
        	if(max>=i)
        	{
        		max = max<(nums[i]+i)?(nums[i]+i):max;
        	}
        }
        return max>=nums.length-1;
    }
}
````
时间复杂度O（n） 空间复杂度O（1）
